FROM nvidia/cuda:11.4.1-cudnn8-runtime-ubuntu20.04

WORKDIR /app

# install requirements
COPY requirements_nlp_app.txt /tmp/

RUN apt-get update\
    && apt-get install -y python3-pip python3\
    && pip install --no-cache-dir install -r /tmp/requirements_nlp_app.txt\
    && pip install jupyter

CMD jupyter notebook --ip 0.0.0.0 --port 8888 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.password=''