version: '3'
services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile.nlp_app 
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
